---

- name: Install MySQL 5.7 repo
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present
  when: mysql_version == 5.7

- name: Install MySQL 8.0 repo
  yum: name=https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm state=present
  when: mysql_version == 8.0

- name: Install MySQL
  yum: pkg={{ item }}
  with_items:
    - mysql-community-server
    - mysql-community-client
    - MySQL-python

- name: Start the MySQL service
  service: name=mysqld state=started enabled=true

- name: mysql_secure_installation
  include: mysql_secure_installation.yml


